// <auto-generated />
using System;
using ContabBackApp.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ContabBackApp.Migrations
{
    [DbContext(typeof(MyDbContext))]
    partial class MyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ContabBackApp.Models.AsientosCabecera", b =>
                {
                    b.Property<int>("IdAsiento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_asiento");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdAsiento"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("descripcion");

                    b.Property<string>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("estado")
                        .HasDefaultValueSql("'Registrado'::character varying");

                    b.Property<DateOnly>("FechaAsiento")
                        .HasColumnType("date")
                        .HasColumnName("fecha_asiento");

                    b.Property<int?>("IdAuxiliar")
                        .HasColumnType("integer")
                        .HasColumnName("id_auxiliar");

                    b.Property<int?>("IdCliente")
                        .HasColumnType("integer")
                        .HasColumnName("id_cliente");

                    b.Property<int?>("IdMoneda")
                        .HasColumnType("integer")
                        .HasColumnName("id_moneda");

                    b.Property<decimal?>("TasaCambio")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("tasa_cambio")
                        .HasDefaultValueSql("1.0000");

                    b.HasKey("IdAsiento")
                        .HasName("asientos_cabecera_pkey");

                    b.HasIndex("IdAuxiliar");

                    b.HasIndex("IdCliente");

                    b.HasIndex("IdMoneda");

                    b.HasIndex(new[] { "FechaAsiento" }, "idx_asientos_fecha");

                    b.ToTable("asientos_cabecera", (string)null);
                });

            modelBuilder.Entity("ContabBackApp.Models.AsientosDetalle", b =>
                {
                    b.Property<int>("IdAsientoDetalle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_asiento_detalle");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdAsientoDetalle"));

                    b.Property<int?>("IdAsiento")
                        .HasColumnType("integer")
                        .HasColumnName("id_asiento");

                    b.Property<int?>("IdCuentaContable")
                        .HasColumnType("integer")
                        .HasColumnName("id_cuenta_contable");

                    b.Property<decimal>("Monto")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("monto");

                    b.Property<string>("TipoMovimiento")
                        .HasMaxLength(2)
                        .HasColumnType("character(2)")
                        .HasColumnName("tipo_movimiento")
                        .IsFixedLength();

                    b.HasKey("IdAsientoDetalle")
                        .HasName("asientos_detalle_pkey");

                    b.HasIndex("IdAsiento");

                    b.HasIndex("IdCuentaContable");

                    b.ToTable("asientos_detalle", (string)null);
                });

            modelBuilder.Entity("ContabBackApp.Models.Auxiliare", b =>
                {
                    b.Property<int>("IdAuxiliar")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_auxiliar");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdAuxiliar"));

                    b.Property<bool?>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("descripcion");

                    b.HasKey("IdAuxiliar")
                        .HasName("auxiliares_pkey");

                    b.ToTable("auxiliares", (string)null);
                });

            modelBuilder.Entity("ContabBackApp.Models.Cliente", b =>
                {
                    b.Property<int>("IdCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_cliente");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdCliente"));

                    b.Property<string>("Cedula")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("cedula");

                    b.Property<string>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("estado")
                        .HasDefaultValueSql("'Activo'::character varying");

                    b.Property<decimal>("LimiteCredito")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("limite_credito")
                        .HasDefaultValueSql("0.00");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.HasKey("IdCliente")
                        .HasName("clientes_pkey");

                    b.HasIndex(new[] { "Cedula" }, "clientes_cedula_key")
                        .IsUnique();

                    b.ToTable("clientes", (string)null);
                });

            modelBuilder.Entity("ContabBackApp.Models.CuentasContable", b =>
                {
                    b.Property<int>("IdCuentaContable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_cuenta_contable");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdCuentaContable"));

                    b.Property<decimal?>("Balance")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("balance")
                        .HasDefaultValueSql("0.00");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("descripcion");

                    b.Property<int?>("IdCuentaPadre")
                        .HasColumnType("integer")
                        .HasColumnName("id_cuenta_padre");

                    b.Property<int?>("IdTipoCuenta")
                        .HasColumnType("integer")
                        .HasColumnName("id_tipo_cuenta");

                    b.Property<int>("Nivel")
                        .HasColumnType("integer")
                        .HasColumnName("nivel");

                    b.Property<bool?>("PermiteMovimiento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("permite_movimiento");

                    b.HasKey("IdCuentaContable")
                        .HasName("cuentas_contables_pkey");

                    b.HasIndex("IdTipoCuenta");

                    b.HasIndex(new[] { "IdCuentaPadre" }, "idx_cuentas_padre");

                    b.ToTable("cuentas_contables", (string)null);
                });

            modelBuilder.Entity("ContabBackApp.Models.Moneda", b =>
                {
                    b.Property<int>("IdMoneda")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_moneda");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdMoneda"));

                    b.Property<string>("CodigoIso")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("codigo_iso");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("descripcion");

                    b.Property<decimal>("TasaCambio")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("tasa_cambio")
                        .HasDefaultValueSql("1.0000");

                    b.HasKey("IdMoneda")
                        .HasName("monedas_pkey");

                    b.HasIndex(new[] { "CodigoIso" }, "monedas_codigo_iso_key")
                        .IsUnique();

                    b.ToTable("monedas", (string)null);
                });

            modelBuilder.Entity("ContabBackApp.Models.TiposCuentum", b =>
                {
                    b.Property<int>("IdTipoCuenta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_tipo_cuenta");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdTipoCuenta"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("descripcion");

                    b.Property<string>("Origen")
                        .HasMaxLength(2)
                        .HasColumnType("character(2)")
                        .HasColumnName("origen")
                        .IsFixedLength();

                    b.HasKey("IdTipoCuenta")
                        .HasName("tipos_cuenta_pkey");

                    b.ToTable("tipos_cuenta", (string)null);
                });

            modelBuilder.Entity("ContabBackApp.Models.TiposDocumento", b =>
                {
                    b.Property<int>("IdTipoDocumento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_tipo_documento");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdTipoDocumento"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("descripcion");

                    b.Property<string>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("estado")
                        .HasDefaultValueSql("'Activo'::character varying");

                    b.Property<int?>("IdCuentaContable")
                        .HasColumnType("integer")
                        .HasColumnName("id_cuenta_contable");

                    b.HasKey("IdTipoDocumento")
                        .HasName("tipos_documento_pkey");

                    b.HasIndex("IdCuentaContable");

                    b.ToTable("tipos_documento", (string)null);
                });

            modelBuilder.Entity("ContabBackApp.Models.TransaccionesCxc", b =>
                {
                    b.Property<int>("IdTransaccion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_transaccion");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdTransaccion"));

                    b.Property<DateOnly>("FechaTransaccion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasColumnName("fecha_transaccion")
                        .HasDefaultValueSql("CURRENT_DATE");

                    b.Property<int?>("IdAsientoGenerado")
                        .HasColumnType("integer")
                        .HasColumnName("id_asiento_generado");

                    b.Property<int?>("IdCliente")
                        .HasColumnType("integer")
                        .HasColumnName("id_cliente");

                    b.Property<int?>("IdTipoDocumento")
                        .HasColumnType("integer")
                        .HasColumnName("id_tipo_documento");

                    b.Property<decimal>("Monto")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("monto");

                    b.Property<string>("NumeroDocumento")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("numero_documento");

                    b.Property<string>("TipoMovimiento")
                        .HasMaxLength(2)
                        .HasColumnType("character(2)")
                        .HasColumnName("tipo_movimiento")
                        .IsFixedLength();

                    b.HasKey("IdTransaccion")
                        .HasName("transacciones_cxc_pkey");

                    b.HasIndex("IdAsientoGenerado");

                    b.HasIndex("IdTipoDocumento");

                    b.HasIndex(new[] { "IdCliente" }, "idx_transacciones_cliente");

                    b.HasIndex(new[] { "FechaTransaccion" }, "idx_transacciones_fecha");

                    b.ToTable("transacciones_cxc", (string)null);
                });

            modelBuilder.Entity("ContabBackApp.Models.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_usuario");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdUsuario"));

                    b.Property<bool?>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<DateTime?>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("IdAuxiliar")
                        .HasColumnType("integer")
                        .HasColumnName("id_auxiliar");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("username");

                    b.HasKey("IdUsuario")
                        .HasName("usuarios_pkey");

                    b.HasIndex("IdAuxiliar");

                    b.HasIndex(new[] { "Username" }, "usuarios_username_key")
                        .IsUnique();

                    b.ToTable("usuarios", (string)null);
                });

            modelBuilder.Entity("ContabBackApp.Models.AsientosCabecera", b =>
                {
                    b.HasOne("ContabBackApp.Models.Auxiliare", "IdAuxiliarNavigation")
                        .WithMany("AsientosCabeceras")
                        .HasForeignKey("IdAuxiliar")
                        .HasConstraintName("asientos_cabecera_id_auxiliar_fkey");

                    b.HasOne("ContabBackApp.Models.Cliente", "IdClienteNavigation")
                        .WithMany("AsientosCabeceras")
                        .HasForeignKey("IdCliente")
                        .HasConstraintName("asientos_cabecera_id_cliente_fkey");

                    b.HasOne("ContabBackApp.Models.Moneda", "IdMonedaNavigation")
                        .WithMany("AsientosCabeceras")
                        .HasForeignKey("IdMoneda")
                        .HasConstraintName("asientos_cabecera_id_moneda_fkey");

                    b.Navigation("IdAuxiliarNavigation");

                    b.Navigation("IdClienteNavigation");

                    b.Navigation("IdMonedaNavigation");
                });

            modelBuilder.Entity("ContabBackApp.Models.AsientosDetalle", b =>
                {
                    b.HasOne("ContabBackApp.Models.AsientosCabecera", "IdAsientoNavigation")
                        .WithMany("AsientosDetalles")
                        .HasForeignKey("IdAsiento")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("asientos_detalle_id_asiento_fkey");

                    b.HasOne("ContabBackApp.Models.CuentasContable", "IdCuentaContableNavigation")
                        .WithMany("AsientosDetalles")
                        .HasForeignKey("IdCuentaContable")
                        .HasConstraintName("asientos_detalle_id_cuenta_contable_fkey");

                    b.Navigation("IdAsientoNavigation");

                    b.Navigation("IdCuentaContableNavigation");
                });

            modelBuilder.Entity("ContabBackApp.Models.CuentasContable", b =>
                {
                    b.HasOne("ContabBackApp.Models.CuentasContable", "IdCuentaPadreNavigation")
                        .WithMany("InverseIdCuentaPadreNavigation")
                        .HasForeignKey("IdCuentaPadre")
                        .HasConstraintName("cuentas_contables_id_cuenta_padre_fkey");

                    b.HasOne("ContabBackApp.Models.TiposCuentum", "IdTipoCuentaNavigation")
                        .WithMany("CuentasContables")
                        .HasForeignKey("IdTipoCuenta")
                        .HasConstraintName("cuentas_contables_id_tipo_cuenta_fkey");

                    b.Navigation("IdCuentaPadreNavigation");

                    b.Navigation("IdTipoCuentaNavigation");
                });

            modelBuilder.Entity("ContabBackApp.Models.TiposDocumento", b =>
                {
                    b.HasOne("ContabBackApp.Models.CuentasContable", "IdCuentaContableNavigation")
                        .WithMany("TiposDocumentos")
                        .HasForeignKey("IdCuentaContable")
                        .HasConstraintName("tipos_documento_id_cuenta_contable_fkey");

                    b.Navigation("IdCuentaContableNavigation");
                });

            modelBuilder.Entity("ContabBackApp.Models.TransaccionesCxc", b =>
                {
                    b.HasOne("ContabBackApp.Models.AsientosCabecera", "IdAsientoGeneradoNavigation")
                        .WithMany("TransaccionesCxcs")
                        .HasForeignKey("IdAsientoGenerado")
                        .HasConstraintName("transacciones_cxc_id_asiento_generado_fkey");

                    b.HasOne("ContabBackApp.Models.Cliente", "IdClienteNavigation")
                        .WithMany("TransaccionesCxcs")
                        .HasForeignKey("IdCliente")
                        .HasConstraintName("transacciones_cxc_id_cliente_fkey");

                    b.HasOne("ContabBackApp.Models.TiposDocumento", "IdTipoDocumentoNavigation")
                        .WithMany("TransaccionesCxcs")
                        .HasForeignKey("IdTipoDocumento")
                        .HasConstraintName("transacciones_cxc_id_tipo_documento_fkey");

                    b.Navigation("IdAsientoGeneradoNavigation");

                    b.Navigation("IdClienteNavigation");

                    b.Navigation("IdTipoDocumentoNavigation");
                });

            modelBuilder.Entity("ContabBackApp.Models.Usuario", b =>
                {
                    b.HasOne("ContabBackApp.Models.Auxiliare", "Auxiliar")
                        .WithMany()
                        .HasForeignKey("IdAuxiliar")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("usuarios_id_auxiliar_fkey");

                    b.Navigation("Auxiliar");
                });

            modelBuilder.Entity("ContabBackApp.Models.AsientosCabecera", b =>
                {
                    b.Navigation("AsientosDetalles");

                    b.Navigation("TransaccionesCxcs");
                });

            modelBuilder.Entity("ContabBackApp.Models.Auxiliare", b =>
                {
                    b.Navigation("AsientosCabeceras");
                });

            modelBuilder.Entity("ContabBackApp.Models.Cliente", b =>
                {
                    b.Navigation("AsientosCabeceras");

                    b.Navigation("TransaccionesCxcs");
                });

            modelBuilder.Entity("ContabBackApp.Models.CuentasContable", b =>
                {
                    b.Navigation("AsientosDetalles");

                    b.Navigation("InverseIdCuentaPadreNavigation");

                    b.Navigation("TiposDocumentos");
                });

            modelBuilder.Entity("ContabBackApp.Models.Moneda", b =>
                {
                    b.Navigation("AsientosCabeceras");
                });

            modelBuilder.Entity("ContabBackApp.Models.TiposCuentum", b =>
                {
                    b.Navigation("CuentasContables");
                });

            modelBuilder.Entity("ContabBackApp.Models.TiposDocumento", b =>
                {
                    b.Navigation("TransaccionesCxcs");
                });
#pragma warning restore 612, 618
        }
    }
}
